---
- hosts: database
  become: true
  tasks:
    - name: install msql-server
      ansible.builtin.dnf:
        name: mariadb-server
        state: present

    - name: enable/start the service
      service:
        name: mariadb
        enabled: yes
        state: started