---
- hosts: database
  become: true
  tasks:
    - name: install msql-server
      ansible.builtin.dnf:
        name: mariadb-server
        state: present

    - name: enable/start the service
      service:
        name: mariadb
        enabled: yes
        state: started

    - name: ensure msql-server listens on all ports
      lineinfile:
        dest: /etc/my.cnf.d/mariadb-server.cnf
        regexp: ^bind-address
        line: "bind-address = 0.0.0.0"
      notify: restart mysql

  handlers: 
    - name: restart mysql
      service:
        name: mariadb
        state: restarted
      