---
- hosts: loadbalancer
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: enable/start the service
      service:
        name: nginx
        enabled: yes
        state: started

    - name: configure nginx site
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/default.d/demo
        mode: 644
        notify: restart nginx

  - handlers:
      - name: restart nginx
        service:
          name: nginx
          enabled: yes
          state: started
