---
- hosts: loadbalancer
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: enable/start the service
      service:
        name: nginx
        enabled: yes
        state: started