---
- hosts: webserver
  ignore_errors: yes
  become: true
  tasks:
    - name: install apache stuff
      ansible.builtin.dnf:
        name: "{{ item }}"
      with_items:
        - httpd
        - mod_wsgi
        - python-pip
        - python3-virtualenv

    - name: enable/start the service
      service:
        name: httpd
        enabled: yes
        state: started

    - name: enable/start mod_wsgi
      apache2_module:
        name: mod_wsgi
        state: present
      notify: restart httpd

    - name: copy demo app source
      copy: src=demo/app/ dest=/var/www/demo mode=0755
      notify: restart httpd

    - name: copy httpd vhost conf
      copy: src=demo/demo.conf dest=/etc/httpd/conf.d/ mode=0755
      notify: restart httpd

    - name: setup python venv
      pip: requirements=/war/www/demo/requirements.txt virtualenv=/var/www/demo/.venv
      notify: restart httpd

  handlers:
    - name: restart httpd
      service:
         name: httpd
         state: restarted     


