---
- hosts: webserver
  ignore_errors: yes
  become: true
  tasks:
    - name: install apache stuff
      ansible.builtin.dnf:
        name: "{{ item }}"
      with_items:
        - httpd
        - mod_wsgi
        - python-pip
        - python3-virtualenv

    - name: enable/start the service
      service:
        name: httpd
        enabled: yes
        state: started

    - name: enable/start mod_wsgi
      apache2_module:
        name: mod_wsgi
        state: present

  handlers:
    - name: restart httpd
      service:
         name: httpd
         state: restarted     


